version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FariaMano10
      POSTGRES_DB: sistlabsolos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-app:
    image: leonardofariaoliveiradev/sistlabsolos-api:latest
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistlabsolos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: FariaMano10
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
